// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateButton('rowButton', { text: 'Add row', onclick: 'incrementRow', rightImageWidth: 20, leftImageWidth: 20 });
    CreateText('title', { text: 'Knitting Row Counter' });
    CreateButton('resetButton', { text: 'Reset', onclick: 'clickReset', rightImageWidth: 11, leftImageWidth: 11 });
    CreateText('rowsRepText', { text: 'Number of rows per repeat' });
    CreateText('totRowsText', { text: 'Total number of rows' });
    CreateText('totRowText', { text: 'Total # rows' });
    CreateText('rowRepText', { text: '# row of repeat' });
    CreateText('currRepeatText', { text: 'Current pattern repeat #' });
    CreateGauge('gauge', { startAngle: 45, maxValue: 100, onValue: 1, pivotOffsetY: 28, pointerReach: 85, criticalValue: 80, warningValue: 50, pivotOffsetX: 28, stopAngle: 315 });
    CreateText('gaugeHalfCompleteText', { text: unescape('50%25') });
    CreateText('gaugeEmptyText', { text: unescape('0%25') });
    CreateText('gaugeCompleteText', { text: unescape('100%25') });
}
window.addEventListener('load', setupParts, false);
